//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpPEP.Repository.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiLog
    {
        public int Id { get; set; }
        public string MethodName { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string IPAddress { get; set; }
        public string UserId { get; set; }
        public string Url { get; set; }
        public string Request { get; set; }
        public string Response { get; set; }
        public string Exception { get; set; }
    }
}
