//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpPEP.Repository.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailTemplateMaster
    {
        public int EmailTemplateId { get; set; }
        public string TemplateName { get; set; }
        public int EventId { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
    }
}
