//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpPEP.Repository.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeKRA_Log
    {
        public long KRALogId { get; set; }
        public string Action { get; set; }
        public Nullable<int> KRAId { get; set; }
        public Nullable<int> AppraisalCycleId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string GoalType { get; set; }
        public string GoalDescription { get; set; }
        public Nullable<decimal> Weightage { get; set; }
        public string ActionStep { get; set; }
        public string Measure { get; set; }
        public Nullable<System.DateTime> TargetDate { get; set; }
        public Nullable<System.DateTime> KRAFromDate { get; set; }
        public Nullable<System.DateTime> KRAToDate { get; set; }
        public Nullable<int> KRAStatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> KRASetId { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public Nullable<int> IsSeen { get; set; }
        public string Selfassesment { get; set; }
    }
}
