//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpPEP.Repository.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAward
    {
        public int AwardId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> AppraisalCycleId { get; set; }
        public string Heading { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> AwardDate { get; set; }
    }
}
