//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpPEP.Repository.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeFeedBack_Log
    {
        public long FeedBackLogId { get; set; }
        public string Action { get; set; }
        public Nullable<int> FeedBackId { get; set; }
        public Nullable<int> AppraisalCycleId { get; set; }
        public Nullable<int> FromEmployeeId { get; set; }
        public Nullable<int> ToEmployeeId { get; set; }
        public Nullable<int> ActionTypeId { get; set; }
        public Nullable<int> AreaID { get; set; }
        public Nullable<int> GradeAreaQuestionMappingID { get; set; }
        public Nullable<int> QuestionaireId { get; set; }
        public string Feedback { get; set; }
        public Nullable<int> ParentFeedBackId { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> FeedbackDate { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<bool> IsIgnore { get; set; }
        public Nullable<int> IsSeen { get; set; }
        public string PerformCycleCheck { get; set; }
    }
}
