//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpPEP.Repository.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeRatingNormailizationDetail
    {
        public int Id { get; set; }
        public Nullable<int> AppraisalCycleId { get; set; }
        public Nullable<int> PEPEmployeeId { get; set; }
        public string Rating { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> RatingGivenBy { get; set; }
        public Nullable<int> RecoForPromotion { get; set; }
        public string Comments { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> DeliveryUnit { get; set; }
        public Nullable<int> NextSkipRM { get; set; }
        public Nullable<bool> IsAdminApproved { get; set; }
        public Nullable<bool> IsShowtoEmployee { get; set; }
        public Nullable<int> SLastRatingGivenBy { get; set; }
        public Nullable<int> ByRoleId { get; set; }
        public Nullable<int> PromotionTrack { get; set; }
        public Nullable<int> ReccomendedDesignation { get; set; }
        public Nullable<int> DesigConsent { get; set; }
    }
}
