//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpPEP.Repository.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTraining
    {
        public int TrainingId { get; set; }
        public Nullable<int> TrainingItemId { get; set; }
        public Nullable<int> AppraisalCycleId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> ActionTypeId { get; set; }
        public Nullable<int> TrainingStatusId { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> SuggestedStartDate { get; set; }
        public Nullable<System.DateTime> SuggestedEndDate { get; set; }
        public Nullable<System.DateTime> ActualStartDate { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public Nullable<int> ParentTrainingId { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> DurationInDays { get; set; }
        public Nullable<int> DurationInHrs { get; set; }
        public Nullable<int> AspireTrainingId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
