//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpPEP.Repository.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeManagerMapping_Log
    {
        public long LogId { get; set; }
        public string Action { get; set; }
        public Nullable<int> Id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> EmployeeManagerId { get; set; }
        public Nullable<int> EmployeeDelegatorId { get; set; }
        public Nullable<int> EmployeeReviewerId { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> CanChangeRecord { get; set; }
        public Nullable<int> ProjectId { get; set; }
    }
}
