//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpPEP.Repository.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpRatingNormPromotionAtReviewerStage
    {
        public int Id { get; set; }
        public Nullable<int> AppraisalCycleId { get; set; }
        public Nullable<int> PEPEmployeeId { get; set; }
        public string Rating { get; set; }
        public Nullable<int> RecoForPromotion { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    }
}
