//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpPEP.Repository.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpRMRatingList
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> EMPDOJ { get; set; }
        public string EMPID { get; set; }
        public string RMID { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string LocationName { get; set; }
        public Nullable<int> GradeId { get; set; }
        public string GradeName { get; set; }
        public Nullable<int> GradeLevel { get; set; }
        public string EmpType { get; set; }
        public string NormEligibility { get; set; }
        public string DPId { get; set; }
        public string GDLId { get; set; }
        public Nullable<int> GroupAccountId { get; set; }
        public string GroupAccountName { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string PromotionDate { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string HRBP1ID { get; set; }
        public string HRBP2ID { get; set; }
        public string HRBP3ID { get; set; }
        public string HRBP4ID { get; set; }
        public string HRBP5ID { get; set; }
        public Nullable<int> PromotionEligibility { get; set; }
        public Nullable<System.DateTime> LastPromotionDate { get; set; }
        public Nullable<int> IsBCTPromApplicable { get; set; }
        public Nullable<int> AppraisalCycleId { get; set; }
        public Nullable<System.DateTime> PromotionDateValue { get; set; }
        public Nullable<int> TotalExpinYrs { get; set; }
        public Nullable<int> TotalExpinmths { get; set; }
        public Nullable<int> InfogainExpinYrs { get; set; }
        public Nullable<int> InfogainExpinMths { get; set; }
    }
}
