//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpPEP.Repository.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackLimitsMaster
    {
        public int FeedbackLimitID { get; set; }
        public Nullable<int> FeedbackFlowLimit { get; set; }
        public Nullable<int> ManagersTotalFeedback { get; set; }
        public Nullable<int> EmployeeTotalFeedback { get; set; }
        public Nullable<int> ClientTotalFeedback { get; set; }
        public Nullable<int> IsActive { get; set; }
    }
}
