//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpPEP.Repository.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoalModificationRequest
    {
        public int RequestId { get; set; }
        public int EmployeeId { get; set; }
        public int AppraisalCycleId { get; set; }
        public string Cycle { get; set; }
        public int ReasonId { get; set; }
        public string Status { get; set; }
        public int RequestCount { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string RejectionReason { get; set; }
    }
}
