//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpPEP.Repository.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeQuestionDetail
    {
        public int GradeQuestionDetailId { get; set; }
        public int GradeQuestionMasterId { get; set; }
        public int QuestionaireId { get; set; }
        public decimal SupervisorWeightage { get; set; }
        public decimal PeerAndCustomerWeightage { get; set; }
        public int Sequence { get; set; }
        public int IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
