//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpPEP.Repository.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeQuestionMaster
    {
        public int GradeQuestionMasterId { get; set; }
        public int CompanyId { get; set; }
        public int AppraisalTypeId { get; set; }
        public string GradeQuestionName { get; set; }
        public string GradeQuestionDescription { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> AppraisalCycleId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
