//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpPEP.Repository.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeAreaQuestionMapping
    {
        public int GradeAreaQuestionMappingID { get; set; }
        public Nullable<int> AppraisalCycleId { get; set; }
        public Nullable<int> AreaID { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public Nullable<int> EmployeeGradeID { get; set; }
        public Nullable<decimal> SupervisorWeightage { get; set; }
        public Nullable<decimal> PeerAndCustomerWeightage { get; set; }
        public string ExpectedPoint { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
