//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpPEP.Repository.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NormalisationGradeAppraisalMapping
    {
        public int Id { get; set; }
        public int AppraisalCycleId { get; set; }
        public int GradeId { get; set; }
        public Nullable<System.DateTime> NormalisationStartDate { get; set; }
        public Nullable<System.DateTime> NormalisationEndDate { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool IsRatingVisible { get; set; }
        public Nullable<System.DateTime> DateCheckBelowDP { get; set; }
        public Nullable<System.DateTime> GDLDateCheck { get; set; }
        public Nullable<System.DateTime> GDLClosureDate { get; set; }
        public Nullable<System.DateTime> DPClosureDate { get; set; }
    }
}
