//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpPEP.Repository.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEPEmployeeRating_log
    {
        public int ID { get; set; }
        public int H_Id { get; set; }
        public Nullable<int> H_AppraisalCycleId { get; set; }
        public string H_EmployeeId { get; set; }
        public string H_Rating { get; set; }
        public Nullable<System.DateTime> H_CreatedOn { get; set; }
        public string H_CreatedBy { get; set; }
        public Nullable<System.DateTime> H_ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string H_AppraisalCycleName { get; set; }
        public string H_RatingDesc { get; set; }
    }
}
