//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpPEP.Repository.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEPLocationWiseRight
    {
        public int id { get; set; }
        public Nullable<int> empid { get; set; }
        public Nullable<int> locationId { get; set; }
        public string createdby { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
    }
}
