//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpPEP.Repository.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEPRatingNormalizationMasterEncryption
    {
        public int ID { get; set; }
        public string Rating { get; set; }
        public string RatingName { get; set; }
        public string Encryptedvalue { get; set; }
        public string RatingBackendValue { get; set; }
        public string RatingTextSeeToEmp { get; set; }
    }
}
