//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpPEP.Repository.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIP_PeriodWeekEmpMappingMaster
    {
        public int WeekId { get; set; }
        public Nullable<int> CycleId { get; set; }
        public Nullable<int> PeriodId { get; set; }
        public Nullable<int> ParameterId { get; set; }
        public Nullable<System.DateTime> WeekStartDate { get; set; }
        public Nullable<System.DateTime> WeekEndDate { get; set; }
        public string Feedback { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> Modifiedby { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> IsMandatory { get; set; }
        public Nullable<int> WeekNo { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
