//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpPEP.Repository.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIP_EmailTemplateMaster
    {
        public int EmailTemplateid { get; set; }
        public string TemplateName { get; set; }
        public Nullable<int> ActionId { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public Nullable<int> ActionTypeId { get; set; }
        public string ActionTypeName { get; set; }
        public string Country { get; set; }
    }
}
