//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpPEP.Repository.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIP_CycleFrequencyDetail
    {
        public int Id { get; set; }
        public Nullable<int> PIPId { get; set; }
        public Nullable<int> CycleId { get; set; }
        public Nullable<int> PIPDurationId { get; set; }
        public string CycleStatus { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Modifiedby { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
