//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpPEP.Repository.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIPEmpListDetail
    {
        public int PIPId { get; set; }
        public Nullable<int> PEPEmployeeId { get; set; }
        public string PIPReason { get; set; }
        public Nullable<int> PIPStatus { get; set; }
        public Nullable<System.DateTime> PIPStartDate { get; set; }
        public Nullable<System.DateTime> PIPEnddate { get; set; }
        public string PIPDocFiles { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string PIPRejectionReason { get; set; }
        public Nullable<System.DateTime> PIPDiscussionDate { get; set; }
    
        public virtual PIP_StatusMaster PIP_StatusMaster { get; set; }
    }
}
