//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpPEP.Repository.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionPercentageYearGenderWise
    {
        public int Id { get; set; }
        public int AppraisalCycleId { get; set; }
        public string GradeeName { get; set; }
        public int GradeId { get; set; }
        public int PromotionPercentage { get; set; }
        public int MalePercentage { get; set; }
        public int FemalePercentage { get; set; }
        public int OthersPercentage { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool IsActive { get; set; }
    }
}
