//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpPEP.Repository.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelfassessmentTableDetail
    {
        public int id { get; set; }
        public Nullable<int> KRAId { get; set; }
        public Nullable<int> AppraisalCycleId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> RM { get; set; }
        public string Selfassesment { get; set; }
        public string YearBreakCheck { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
