//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpPEP.Repository.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExceptionLogging
    {
        public long logId { get; set; }
        public string sectionName { get; set; }
        public string controllerName { get; set; }
        public string exceptionMsg { get; set; }
        public string exceptionType { get; set; }
        public string exceptionSource { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public string createdBy { get; set; }
    }
}
