//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpPEP.Repository.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPIPEmployeeParameterDetail
    {
        public int ParameterId { get; set; }
        public Nullable<int> PIPId { get; set; }
        public string ProblemIssue { get; set; }
        public string Deliverables { get; set; }
        public string ProgressMeasurement { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> Modifiedby { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
