//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpPEP.Repository.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadKRAMaster
    {
        public int UploadKRAId { get; set; }
        public string KRATitle { get; set; }
        public string GoalType { get; set; }
        public string GoalDescription { get; set; }
        public Nullable<decimal> Weightage { get; set; }
        public string ActionStep { get; set; }
        public string Measure { get; set; }
        public Nullable<System.DateTime> TargetDate { get; set; }
        public System.DateTime KRAFromDate { get; set; }
        public System.DateTime KRAToDate { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> UploadKRASetID { get; set; }
    }
}
