//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpPEP.Repository.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerticalHorizontalMaster
    {
        public int VerticalHorizontalId { get; set; }
        public int AspireVerticalHorizontalId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string VerticalHorizontalName { get; set; }
        public string VerticalHorizontalDescription { get; set; }
        public Nullable<int> VerticalHorizontalHead { get; set; }
        public int VerticalHorizontal { get; set; }
        public int IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
