//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpPEP.UI.Views.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Master {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Master() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PEP.Views.Admin.Master", typeof(Master).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appraisal Cycle Description.
        /// </summary>
        public static string strAppraisalCycleDesc {
            get {
                return ResourceManager.GetString("strAppraisalCycleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppraisalCycleId.
        /// </summary>
        public static string strAppraisalCycleId {
            get {
                return ResourceManager.GetString("strAppraisalCycleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appraisal Cycle Name.
        /// </summary>
        public static string strAppraisalCycleName {
            get {
                return ResourceManager.GetString("strAppraisalCycleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appraisal Period.
        /// </summary>
        public static string strAppraisalPeriod {
            get {
                return ResourceManager.GetString("strAppraisalPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appraisal Type.
        /// </summary>
        public static string strAppraisalType {
            get {
                return ResourceManager.GetString("strAppraisalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Award Date.
        /// </summary>
        public static string strAwardDate {
            get {
                return ResourceManager.GetString("strAwardDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Award Description.
        /// </summary>
        public static string strAwardDescription {
            get {
                return ResourceManager.GetString("strAwardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Award Heading.
        /// </summary>
        public static string strAwardHeading {
            get {
                return ResourceManager.GetString("strAwardHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AwardId.
        /// </summary>
        public static string strAwardId {
            get {
                return ResourceManager.GetString("strAwardId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string strClear {
            get {
                return ResourceManager.GetString("strClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string strCompany {
            get {
                return ResourceManager.GetString("strCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string strDelete {
            get {
                return ResourceManager.GetString("strDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Deleted!.
        /// </summary>
        public static string strDeleteMsg {
            get {
                return ResourceManager.GetString("strDeleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string strEmployeeName {
            get {
                return ResourceManager.GetString("strEmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Employee Code.
        /// </summary>
        public static string strEmployeeNewCode {
            get {
                return ResourceManager.GetString("strEmployeeNewCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Employee Code.
        /// </summary>
        public static string strEmployeeOldCode {
            get {
                return ResourceManager.GetString("strEmployeeOldCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string strEmployeeRole {
            get {
                return ResourceManager.GetString("strEmployeeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields need to be filled..
        /// </summary>
        public static string strEmptyFieldValidation {
            get {
                return ResourceManager.GetString("strEmptyFieldValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string strEndDate {
            get {
                return ResourceManager.GetString("strEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error occured!.
        /// </summary>
        public static string strErrorMsg {
            get {
                return ResourceManager.GetString("strErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string strInsert {
            get {
                return ResourceManager.GetString("strInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Inserted!.
        /// </summary>
        public static string strInsertSuccess {
            get {
                return ResourceManager.GetString("strInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsActive.
        /// </summary>
        public static string strIsActive {
            get {
                return ResourceManager.GetString("strIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationId.
        /// </summary>
        public static string strLocationId {
            get {
                return ResourceManager.GetString("strLocationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string strLocationName {
            get {
                return ResourceManager.GetString("strLocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManagerId.
        /// </summary>
        public static string strManagerId {
            get {
                return ResourceManager.GetString("strManagerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string strManagerName {
            get {
                return ResourceManager.GetString("strManagerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string strStartDate {
            get {
                return ResourceManager.GetString("strStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string strStatus {
            get {
                return ResourceManager.GetString("strStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string strUpdate {
            get {
                return ResourceManager.GetString("strUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Updated!.
        /// </summary>
        public static string strUpdateSuccess {
            get {
                return ResourceManager.GetString("strUpdateSuccess", resourceCulture);
            }
        }
    }
}
