//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpPEP.UI.Views.KRA {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class KRA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KRA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PEP.Views.KRA.KRA", typeof(KRA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Step.
        /// </summary>
        public static string strActionStep {
            get {
                return ResourceManager.GetString("strActionStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal.
        /// </summary>
        public static string strGoalDesc {
            get {
                return ResourceManager.GetString("strGoalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Type.
        /// </summary>
        public static string strGoalType {
            get {
                return ResourceManager.GetString("strGoalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string strKRAApprove {
            get {
                return ResourceManager.GetString("strKRAApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string strKRAClear {
            get {
                return ResourceManager.GetString("strKRAClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter dates betweeen.
        /// </summary>
        public static string strKRADateValidation {
            get {
                return ResourceManager.GetString("strKRADateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string strKRADelete {
            get {
                return ResourceManager.GetString("strKRADelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record deleted!.
        /// </summary>
        public static string strKRADeleteSuccessMsg {
            get {
                return ResourceManager.GetString("strKRADeleteSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string strKRAEdit {
            get {
                return ResourceManager.GetString("strKRAEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields need to be filled..
        /// </summary>
        public static string strKRAEmptyFieldValidation {
            get {
                return ResourceManager.GetString("strKRAEmptyFieldValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string strKRAEndDate {
            get {
                return ResourceManager.GetString("strKRAEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error occured!.
        /// </summary>
        public static string strKRAErrorMsg {
            get {
                return ResourceManager.GetString("strKRAErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string strKRAInsert {
            get {
                return ResourceManager.GetString("strKRAInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record inserted!.
        /// </summary>
        public static string strKRAInsertSuccessMsg {
            get {
                return ResourceManager.GetString("strKRAInsertSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This employee hasn&apos;t filled KRA..
        /// </summary>
        public static string strKRANotFilled {
            get {
                return ResourceManager.GetString("strKRANotFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This employee hasn&apos;t submitted KRA..
        /// </summary>
        public static string strKRANotSubmitted {
            get {
                return ResourceManager.GetString("strKRANotSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter weightage value between.
        /// </summary>
        public static string strKRANumberRangeValidation {
            get {
                return ResourceManager.GetString("strKRANumberRangeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string strKRAReject {
            get {
                return ResourceManager.GetString("strKRAReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string strKRAStartDate {
            get {
                return ResourceManager.GetString("strKRAStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string strKRAStatus {
            get {
                return ResourceManager.GetString("strKRAStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string strKRAStatusApproved {
            get {
                return ResourceManager.GetString("strKRAStatusApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string strKRAStatusCompleted {
            get {
                return ResourceManager.GetString("strKRAStatusCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialised.
        /// </summary>
        public static string strKRAStatusInitialised {
            get {
                return ResourceManager.GetString("strKRAStatusInitialised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string strKRAStatusRejected {
            get {
                return ResourceManager.GetString("strKRAStatusRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        public static string strKRAStatusSubmitted {
            get {
                return ResourceManager.GetString("strKRAStatusSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string strKRASubmit {
            get {
                return ResourceManager.GetString("strKRASubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exceeds character count. Characters to reduce :  .
        /// </summary>
        public static string strKRATextAreaLengthValidation {
            get {
                return ResourceManager.GetString("strKRATextAreaLengthValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string strKRAUpdate {
            get {
                return ResourceManager.GetString("strKRAUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record updated!.
        /// </summary>
        public static string strKRAUpdateSuccessMsg {
            get {
                return ResourceManager.GetString("strKRAUpdateSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total weightage should be 100 to finalize the Goals..
        /// </summary>
        public static string strKRAWeigthageValidation {
            get {
                return ResourceManager.GetString("strKRAWeigthageValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure.
        /// </summary>
        public static string strMeasure {
            get {
                return ResourceManager.GetString("strMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please mark the previous set of KRA as complete before inserting new one..
        /// </summary>
        public static string strPrevKRAValidation {
            get {
                return ResourceManager.GetString("strPrevKRAValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sr. No..
        /// </summary>
        public static string strSeqNo {
            get {
                return ResourceManager.GetString("strSeqNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Date (by When).
        /// </summary>
        public static string strTargetDate {
            get {
                return ResourceManager.GetString("strTargetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weightage(%).
        /// </summary>
        public static string strWeightage {
            get {
                return ResourceManager.GetString("strWeightage", resourceCulture);
            }
        }
    }
}
